### ISSUE TITLE
Fix API-problems in grover-branch

### ISSUE THREAD

**Issue by jmarre1** [czachow/qcmb-training#37]
qobj = assemble(grover_circuit_sim)
result = sim.run(qobj).result()

These calls are not compatible with the Qiskit-version on IBM-quantum

**Comment by czachow** [comment]
There is a bug in the assemble method. But it is possible to use the 'run' method directly.
Thus the new code would look like:
```
grover_circuit_sim = ...
result = sim.run(grover_circuit_sim).result()
```
