### ISSUE TITLE
Grover-branch: Handle IBMQ.load_account() problem on Github

### ISSUE THREAD

**Issue by jmarre1** [czachow/qcmb-training#38]
The new calls
IBMQ.load_account() 
in the grover-branch will not work in the environment of the automation workflow on Github. 
This case has to be handled. 
May be comment out all calls??

**Comment by czachow** [comment]
We have a test account for the IBM Quantum Experience. I put the credentials as secrets for the CI pipeline and changed the CI script. Now the secrets are pulled and the pipeline is fixed.
